export const VISIT_TOUR_AVG_SPEED_KMH = 45;
export const VISIT_TOUR_STOP_MINUTES = 15;
export const VISIT_TOUR_DEFAULT_MAX_DURATION_MIN = 480;
export const VISIT_TOUR_DEFAULT_MAX_STOPS = 8;
export const VISIT_TOUR_DEFAULT_MAX_DEVIATION_KM = 5;
